Get deploy working for ruby 1.9.2
When I tried running this in Ruby 1.9.2 I got the error:

undefined method `to_ruby' for #<Syck::Map:0x007fd625e11948>

This fixes that by using load_file which is supported across the
different ruby versions. (I've tested with 1.8.7, 1.9.2 and 1.9.3)